name: Deploy to Railway

on:
  release:
    types: [published] # Triggers when a release is published on GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production # Use the production environment for enhanced security
    container: ghcr.io/railwayapp/cli:latest # Run the job inside the Railway CLI Docker container
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_NAME }} --detach
