name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  # release:
  #   needs: build
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build release binary
  #       run: cargo build --release --verbose
  #     - name: Create archive
  #       run: tar -C target/release -czvf rust-ping-pong.tar.gz rust-ping-pong
  #     - name: Release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         files: rust-ping-pong.tar.gz
